# Generated by Django 4.2 on 2023-05-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_contexto', models.CharField(max_length=50, null=True, unique=True)),
                ('tipo', models.CharField(max_length=50, unique=True)),
                ('contenido', models.CharField(max_length=550, unique=True)),
            ],
        ),
    ]
